### ISSUE TITLE
Unable to update apk in Galaxy S7 (Android Version 7)

### ISSUE THREAD

**Issue by mkamayd** [vaenow/cordova-plugin-app-update#42]
This plugin is awesome and does work fine in many android devices. I am having issues only with multiples Galxy S7 devices running android 7.0
The pop up is launched but after downloading the apk the app crashed and does not perform the install. These keep happening every time you open the app. I am allowing unknown sources and un-checking the flag that in these device ask if you want to install only once the apk. 
Thanks for the help.

**Comment by hhafeng** [comment]
http://blog.csdn.net/leilifengxingmw/article/details/57405908这里有解决方案

**Comment by arthursp** [comment]
Resolved with last version I think

**Comment by arthurflor** [comment]
Still crashing :/

**Comment by LanceJenkinZA** [comment]
The problem is in [plugin.xml](https://github.com/vaenow/cordova-plugin-app-update/blob/master/plugin.xml#L29).

The provider's authorities is set to `com.vaenow.appupdate.android.provider.${applicationId}`, but the code in [DownloadHandler.java](https://github.com/vaenow/cordova-plugin-app-update/blob/master/src/android/DownloadHandler.java#L96) is calling with "com.vaenow.appupdate.android.provider" - i.e no application id.

I've created a pull request to fix the issue; https://github.com/vaenow/cordova-plugin-app-update/pull/66

**Comment by oceantear** [comment]
I also reproduced this issue on Samsuang Galaxy Tab A with Android 7.0
Even if, I update to v1.4.10. This issue still not been solved.
Below is the Android log:

E/AndroidRuntime: FATAL EXCEPTION: JavaBridge
                                                                        Process: packageName, PID: 20227
                                                                        android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE dat=content://com.vaenow.appupdate.android.provider/download/v2.0 flg=0x1 launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
                                                                            at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
                                                                            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
                                                                            at android.app.Activity.startActivityForResult(Activity.java:4403)
                                                                            at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:342)
                                                                            at android.app.Activity.startActivityForResult(Activity.java:4362)
                                                                            at android.app.Activity.startActivity(Activity.java:4686)
                                                                            at android.app.Activity.startActivity(Activity.java:4654)
                                                                            at com.vaenow.appupdate.android.DownloadHandler.installApk(DownloadHandler.java:106)
                                                                            at com.vaenow.appupdate.android.DownloadHandler.handleMessage(DownloadHandler.java:57)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by dinglicoding** [comment]
In Android Emulater(android 7.0)
i updated app but error:
 E/AndroidRuntime: FATAL EXCEPTION: JavaBridge
                                                                    Process: com.company.crownapp, PID: 4163
                                                                    android.os.FileUriExposedException: file:///storage/emulated/0/download/crownapp28 exposed beyond app through Intent.getData()
                                                                        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                                        at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                                        at android.content.Intent.prepareToLeaveProcess(Intent.java:8933)
                                                                        at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4224)
                                                                        at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:342)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                        at android.app.Activity.startActivity(Activity.java:4507)
                                                                        at android.app.Activity.startActivity(Activity.java:4475)
                                                                        at com.vaenow.appupdate.android.DownloadHandler.installApk(DownloadHandler.java:94)
                                                                        at com.vaenow.appupdate.android.DownloadHandler.handleMessage(DownloadHandler.java:54)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
11-16 22:28:39.567 4163-4193/com.company.crownapp E/ConnectivityManager.CallbackHandler: callback not found for RELEASED message
11-16 22:28:39.651 4163-4204/com.company.crownapp E/chromium: [ERROR:gles2_cmd_decoder.cc(2167)] [.CommandBufferContext.RenderCompositor-0xa885bf20]GL ERROR :GL_INVALID_OPERATION : BackFramebuffer::Destroy: <- error from previous GL command

**Comment by dinglicoding** [comment]
@vaenow  hi ,can you help me check what's wrong?

**Comment by Immortalt** [comment]
Still crashing :/

**Comment by JoxC** [comment]
> Still crashing :/

Maybe you need check proguard if you use it. Add lines like below may get things work,
`-keep class xxxx.xxxx.BuildConfig { *; }`
